insert into tipo_usuario (descricao, id_interliga_log_sistemas) values ('administrador', (SELECT T1.id_interliga_log_sistemas FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('cadastro',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('cadusuario',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('cadtipo_usuario',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('caddepartamento',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('alterpermissoes',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('servicosbase',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('cadServicoAutomotivo',true, (SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('cadTipoFornecedor',true,(SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('cadFornecedor',true,(SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into permissao (descricao,autorizacao, id_interliga_log_sistemas) values ('menuDesenvolvedor',true,(SELECT T1.id FROM usuario T1 WHERE T1.login = 'admin'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'cadastro'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'cadusuario'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'cadtipo_usuario'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'caddepartamento'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'alterpermissoes'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'servicosbase'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'cadServicoAutomotivo'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'cadTipoFornecedor'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'cadFornecedor'));
insert into tipo_usuario_permissao (tipousuarios_id,permissao_id) values ((SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador'), (SELECT t1.id FROM permissao t1 WHERE t1.descricao = 'menuDesenvolvedor'));
UPDATE usuario SET id_tipo_usuario=1 WHERE id= (SELECT t1.id FROM tipo_usuario t1 WHERE t1.descricao = 'administrador') AND login = 'admin';